### ISSUE TITLE
Cannot find module when open the app

### ISSUE THREAD

**Issue by Sweet-KK** [cawa-93/vite-electron-builder#934] opened 2023-05-12 07:20 UTC
**Describe the bug**
when I open the app, show this error:

Uncaught Exception:
Error: Cannot find module 'form-data'
Require stack:
- /Users/jin10/Desktop/dev/company/
jin10_vision_electron/dist/mac-
arm64/xxxx.app/Contents/
Resources/app/node_modules/axios/
dist/node/axios.cjs

After installed form-data, show Cannot find other module, It's all dependence on dependence not found, endless, can't be solved

**Expected behavior**
no error.

**Additional context**
"electron": "24.1.3",
"electron-builder": "23.6.0",
"vite": "4.3.3",
"axios": "^1.4.0",

**Comment by happenslol** [comment] 2024-01-07 19:46
I'm having the same issue. From what I can tell, only dependencies that are included in `dependencies` in `package.json` are included. I didn't have many dependencies in there, so I was able to fix the issue by manually including all dependencies of the `main` package there, but it gets impossible quickly since even transitive dependencies have to be included manually there.

This template is amazing, but dependencies not being included correctly for `main` makes this unusable for projects importing a lot of dependencies there 😕

**Comment by cawa-93** [comment] 2024-01-20 12:18
From now on, the template uses native ESMs to resolve modules. I'll close this for now. If the issue is still relevant with the latest changes, feel free to open a new report.

**Closed by cawa-93** 2024-01-20 12:18 UTC
Labels: bug, help wanted
