### ISSUE TITLE
Error resource 404 with ttf and woff files only in develop but in production all work good

### ISSUE THREAD

**Issue by luffynando** [cawa-93/vite-electron-builder#124] opened 2021-02-28 04:31 UTC
### Steps for reproduce problem

git clone this
npm install
npm i element-plus

modify file in /src/renderer/index.ts

```js
import { createApp } from 'vue';
import ElementPlus from 'element-plus';
import locale from 'element-plus/lib/locale/lang/es';
import App from './App.vue';
import router from '/@/router';
import 'dayjs/locale/es';

const app = createApp(App);
app.use(ElementPlus, { size: 'medium', locale });
app.use(router);

app.mount('#app');
```

add in file /src/renderer/App.vue
```
<i class="el-icon-edit"></i>
```

And finally run:
``` 
npm run watch
``` 

And ready in console.log show this error.

![image](https://user-images.githubusercontent.com/22108070/109407867-06968280-794a-11eb-9b84-039a880f1165.png)

**Comment by cawa-93** [comment] 2021-02-28 15:11
I was unable to reproduce your issue. But I think it will be fixed [here](https://github.com/vitejs/vite/pull/2309). I close this issue. If the problem persists after the upgrade, open it again.

**Closed by cawa-93** 2021-02-28 15:11 UTC
