### ISSUE TITLE
Add IPCHash.vue

### ISSUE THREAD

**Issue by Osiris-Team** [cawa-93/vite-electron-builder#956] opened 2023-09-18 14:46 UTC
I think that IPC/[Inter-Process Communication](https://www.electronjs.org/docs/latest/tutorial/ipc) is probably one of the most important things in Electron and that this template should also provide an example Vue component for this.

As base the existing ReactiveHash.vue component can be used, and modified to work via IPC.

**Comment by cawa-93** [comment] 2023-09-18 16:01
The main idea of the ReactiveHash.vue component is to show how to use Node.js API without using IPC.

**Comment by Osiris-Team** [comment] 2023-09-18 16:11
@cawa-93 As I understood this should only work for functions in preload and not main?
I used that approach and tried to create new objects that are defined in main, which compiles, but fails at runtime.
I also need something that is more like events instead of functions I guess.

**Comment by Osiris-Team** [comment] 2023-09-19 07:55
@cawa-93 also, computed() doesnt seem to work with async functions, which is a big issue.
`Uncaught (in promise) Error: Cannot read properties of undefined (reading 'emit')`

**Comment by Osiris-Team** [comment] 2023-09-28 11:21
@cawa-93 Another thing I noticed, that the function you are exporting in preload cannot access fields or methods from the main process like app.getAppPath() is undefined.

**Comment by cawa-93** [comment] 2024-01-20 12:18
From now on, the template uses native ESMs to resolve modules. I'll close this for now. If the issue is still relevant with the latest changes, feel free to open a new report.

**Closed by cawa-93** 2024-01-20 12:18 UTC
Labels: enhancement
