### ISSUE TITLE
Using interprocess package does not load types correctly in renderer

### ISSUE THREAD

**Issue by elis** [cawa-93/vite-electron-builder#910] opened 2023-02-23 07:53 UTC
**Describe the bug**
When using `interprocess` (https://github.com/daltonmenezes/interprocess) package to manage IPC calls the `window.api` does not properly transfer types, and `window.api` is declared as `any`.

**To Reproduce**

1. Add `interprocess` to dependencies
2. Follow instructions to include `interprocess` in main/preload/renderer
3. Use `const { invoke } = window.api`
4. No types available, `window.api.invoke` is declared as `any`

**Expected behavior**
According to boilerplate example from `interprocess` types should be available: https://codesandbox.io/s/advanced-4qh0xb?file=/src/renderer.ts

**Comment by cawa-93** [comment] 2024-01-20 12:19
From now on, the template uses native ESMs to resolve modules. I'll close this for now. If the issue is still relevant with the latest changes, feel free to open a new report.

**Closed by cawa-93** 2024-01-20 12:19 UTC
Labels: bug
